<template>
  <div>
    <VRow>
      <VCol
        cols="12"
        sm="4"
      >
        <VCheckbox
          model-value="red"
          label="red"
          color="red"
          value="red"
        />
        <VCheckbox
          model-value="red-darken-3"
          label="red-darken-3"
          color="red-darken-3"
          value="red-darken-3"
        />
      </VCol>
      <VCol
        cols="12"
        sm="4"
      >
        <VCheckbox
          model-value="indigo"
          label="indigo"
          color="indigo"
          value="indigo"
        />
        <VCheckbox
          model-value="indigo-darken-3"
          label="indigo-darken-3"
          color="indigo-darken-3"
          value="indigo-darken-3"
        />
      </VCol>
      <VCol
        cols="12"
        sm="4"
      >
        <VCheckbox
          model-value="orange"
          label="orange"
          color="orange"
          value="orange"
        />
        <VCheckbox
          model-value="orange-darken-3"
          label="orange-darken-3"
          color="orange-darken-3"
          value="orange-darken-3"
        />
      </VCol>
    </VRow>

    <VRow class="mt-6">
      <VCol
        cols="12"
        sm="4"
      >
        <VCheckbox
          model-value="primary"
          label="primary"
          color="primary"
          value="primary"
        />
        <VCheckbox
          model-value="secondary"
          label="secondary"
          color="secondary"
          value="secondary"
        />
      </VCol>
      <VCol
        cols="12"
        sm="4"
      >
        <VCheckbox
          model-value="success"
          label="success"
          color="success"
          value="success"
        />
        <VCheckbox
          model-value="info"
          label="info"
          color="info"
          value="info"
        />
      </VCol>
      <VCol
        cols="12"
        sm="4"
      >
        <VCheckbox
          model-value="warning"
          label="warning"
          color="warning"
          value="warning"
        />
        <VCheckbox
          model-value="error"
          label="error"
          color="error"
          value="error"
        />
      </VCol>
    </VRow>
  </div>
</template>
