<template>
  <VTabs center-active>
    <VTab>One</VTab>
    <VTab>Two</VTab>
    <VTab>Three</VTab>
    <VTab>Four</VTab>
    <VTab>Five</VTab>
    <VTab>Six</VTab>
    <VTab>Seven</VTab>
    <VTab>Eight</VTab>
    <VTab>Nine</VTab>
    <VTab>Ten</VTab>
    <VTab>Eleven</VTab>
    <VTab>Twelve</VTab>
    <VTab>Thirteen</VTab>
    <VTab>Fourteen</VTab>
    <VTab>Fifteen</VTab>
    <VTab>Sixteen</VTab>
    <VTab>Seventeen</VTab>
    <VTab>Eighteen</VTab>
    <VTab>Nineteen</VTab>
    <VTab>Twenty</VTab>
  </VTabs>
</template>
