<template>
  <VRow>
    <VCol
      cols="12"
      sm="6"
    >
      <VTextarea
        label="One row"
        auto-grow
        variant="outlined"
        rows="1"
        row-height="15"
      />
    </VCol>
    <VCol
      cols="12"
      sm="6"
    >
      <VTextarea
        variant="filled"
        auto-grow
        label="Two rows"
        rows="2"
        row-height="20"
      />
    </VCol>
    <VCol
      cols="12"
      sm="6"
    >
      <VTextarea
        label="Three rows"
        auto-grow
        variant="outlined"
        rows="3"
        row-height="25"
        shaped
      />
    </VCol>
    <VCol
      cols="12"
      sm="6"
    >
      <VTextarea
        variant="filled"
        auto-grow
        label="Four rows"
        rows="4"
        row-height="30"
        shaped
      />
    </VCol>
  </VRow>
</template>
