<template>
  <VRow>
    <VCol
      cols="12"
      sm="4"
      md="4"
    >
      <VSwitch
        model-value="red"
        label="red"
        color="red"
        value="red"
      />
      <VSwitch
        model-value="red-darken-3"
        label="red-darken-3"
        color="red-darken-3"
        value="red-darken-3"
      />
    </VCol>
    <VCol
      cols="12"
      sm="4"
      md="4"
    >
      <VSwitch
        model-value="indigo"
        label="indigo"
        color="indigo"
        value="indigo"
      />
      <VSwitch
        model-value="indigo-darken-3"
        label="indigo-darken-3"
        color="indigo-darken-3"
        value="indigo-darken-3"
      />
    </VCol>
    <VCol
      cols="12"
      sm="4"
      md="4"
    >
      <VSwitch
        model-value="orange"
        label="orange"
        color="orange"
        value="orange"
      />
      <VSwitch
        model-value="orange-darken-3"
        label="orange-darken-3"
        color="orange-darken-3"
        value="orange-darken-3"
      />
    </VCol>
  </VRow>

  <VRow class="mt-6">
    <VCol
      cols="12"
      sm="4"
      md="4"
    >
      <VSwitch
        model-value="primary"
        label="primary"
        color="primary"
        value="primary"
      />
      <VSwitch
        model-value="secondary"
        label="secondary"
        color="secondary"
        value="secondary"
      />
    </VCol>
    <VCol
      cols="12"
      sm="4"
      md="4"
    >
      <VSwitch
        model-value="success"
        label="success"
        color="success"
        value="success"
      />
      <VSwitch
        model-value="info"
        label="info"
        color="info"
        value="info"
      />
    </VCol>
    <VCol
      cols="12"
      sm="4"
      md="4"
    >
      <VSwitch
        model-value="warning"
        label="warning"
        color="warning"
        value="warning"
      />
      <VSwitch
        model-value="error"
        label="error"
        color="error"
        value="error"
      />
    </VCol>
  </VRow>
</template>
